import type { Theme } from "../lib/theme-types";

export const cursor: Theme = {
  id: "cursor",
  name: "Cursor",
  description: "A dark theme inspired by the Cursor editor.",
  editorTheme: { dark: "copilot", light: "github-light" },
  variants: {
    dark: {
      colors: {
        background: "#0a0a0c",
        foreground: "#E0E0E0",
        card: "#121215",
        cardForeground: "#E0E0E0",
        popover: "#121215",
        popoverForeground: "#E0E0E0",
        primary: "#3E8FB0",
        primaryForeground: "#ffffff",
        secondary: "#121215",
        secondaryForeground: "#E0E0E0",
        muted: "#18181c",
        mutedForeground: "#757575",
        accent: "#18181c",
        accentForeground: "#E0E0E0",
        destructive: "#e54d2e",
        border: "#1d1d22",
        input: "#1d1d22",
        ring: "#3E8FB0",
        sidebar: "#0a0a0c",
        sidebarForeground: "#E0E0E0",
        sidebarPrimary: "#3E8FB0",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#121215",
        sidebarAccentForeground: "#E0E0E0",
        sidebarBorder: "#1d1d22",
        sidebarRing: "#3E8FB0",
        radius: "0.5rem",
      },
      terminal: {
        cursor: "#3E8FB0",
        cursorAccent: "#0a0a0c",
        selection: "rgba(62, 143, 176, 0.20)",
        ansi: [
          "#121212", "#FF8080", "#95FFA4", "#FFFF9E",
          "#3E8FB0", "#FF9BFF", "#9BFFFF", "#E0E0E0",
          "#4D4D4B", "#FF6E6E", "#69FF94", "#FFFFA5",
          "#D6ACFF", "#FF92DF", "#A4FFFF", "#FFFFFF",
        ],
      },
    },
    light: {
      colors: {
        background: "#FFFFFF",
        foreground: "#111827",
        card: "#F8F9FA",
        cardForeground: "#111827",
        popover: "#F8F9FA",
        popoverForeground: "#111827",
        primary: "#007BFF",
        primaryForeground: "#ffffff",
        secondary: "#F8F9FA",
        secondaryForeground: "#111827",
        muted: "#E9ECEF",
        mutedForeground: "#4B5563",
        accent: "#E9ECEF",
        accentForeground: "#111827",
        destructive: "#e54d2e",
        border: "#E9ECEF",
        input: "#E9ECEF",
        ring: "#007BFF",
        sidebar: "#FFFFFF",
        sidebarForeground: "#111827",
        sidebarPrimary: "#007BFF",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#F8F9FA",
        sidebarAccentForeground: "#111827",
        sidebarBorder: "#E9ECEF",
        sidebarRing: "#007BFF",
        radius: "0.5rem",
      },
      terminal: {
        cursor: "#007BFF",
        cursorAccent: "#FFFFFF",
        selection: "rgba(0, 123, 255, 0.15)",
        ansi: [
          "#111827", "#DC3545", "#28A745", "#D39E00",
          "#007BFF", "#BD2130", "#17A2B8", "#FFFFFF",
          "#4D4D4B", "#FF6E6E", "#69FF94", "#FFFFA5",
          "#D6ACFF", "#FF92DF", "#A4FFFF", "#FFFFFF",
        ],
      },
    },
  },
};
